language: rust

env:
  global:
    - secure: pQJkfFtkEXSTb/rx0rRbP9zuAbCI2NzEFNylWJlhGR3TN/bKo/RwDdl1Lc0L4JYFOxdk8hjNLSWJKA148+y4hU4rrkPX9NyfnUdbLz5vm6900PkT/aG8dceVWudkueC9fT0n4S67256DjkkTzhTwsdp8CBbrzgj/W7SAO8jZwv4=

before_install:
  # This PPA has a newer version of gnuplot
  - sudo add-apt-repository ppa:gladky-anton/precise-backports -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gnuplot

script:
  - cargo build --verbose
  - cargo bench --verbose -- --test
  - cargo doc --verbose && mv target/doc doc
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh'

branches:
  only: master
