sudo: false
language: rust
rust: nightly

env:
  global:
    - secure: gPGjVs0jJTU1ZbYG0LapuP6bwaQ79ao9wYMrqwLYwgkiLfDAcsJXHecp0PUUGCJnEZvAzv9hhjsmGpgACMc6h718gHnXcXdZFyXPeW0SLHl8ZBOAX84GqAbENXv33O6BmiYgti3ao5a3pLXBTUZIC6sTZiAuFTksdizLAUa/i/4=

matrix:
  include:
    - env: GNUPLOT=yes
      addons:
        apt:
          packages:
            - gnuplot

script:
  - cargo build --verbose
  - cargo bench --verbose -- --test --nocapture
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master

notifications:
  email:
    on_success: never
