sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - gnuplot

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install gnuplot;
    fi

script:
  - cargo build
  - cargo test
  - cargo doc

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      travis-cargo --only stable doc-upload;
    fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: C2Oij4OPM2pdkbpEV6bsCJ8PpqDk2NtjFhFiO+4ZlYrRCQnbv+TAOuWNj5aX1EOWPlMQdP/95VrEOizUcK1twsCuc6d8PnAoCu8WnLRsOSO8GftVynC+CEJSnaDpAVO3N23f5jrCsKQhZx9R/hADpY5ni2ik0rKNWGllaYzuUCc=

branches:
  only: master

notifications:
  email:
    on_success: never
