language: rust

env:
  global:
    - secure: d7cJ0SnqKtJ1hO+23z5zdqHcvZpgooayhiCViGEWnu5KXkxVM2B+JTyvVcui8xskjG/q4FnrTHsn2qHX1416RW4JVX+z9xARWWISZGB3bTVMIrrk2NchafZBMwFqL6N/PwqYhU16zKllRUkEXOjcf9SpxKK/7Vl6i1uIU/+2o8o=
  matrix:
    - WITH_GNUPLOT=true
    - WITH_GNUPLOT=false

before_install:
  # This PPA has a newer version of gnuplot
  - if [[ $WITH_GNUPLOT == 'true' ]]; then
      sudo add-apt-repository ppa:gladky-anton/precise-backports -y;
      sudo apt-get update -qq;
    fi

install:
  - if [[ $WITH_GNUPLOT == 'true' ]]; then
      sudo apt-get install -qq gnuplot;
    fi

script:
  - cargo build --verbose
  - cargo bench --verbose -- --test --nocapture
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
