sudo: false

language: rust

rust: nightly

os:
  - linux
  - osx

matrix:
  # Clear the whole matrix
  exclude:
    - os: linux
    - os: osx
  # Add each target manually
  include:
    - os: linux
      env: GNUPLOT=no
    - os: linux
      env: GNUPLOT=yes
      addons:
        apt:
          packages:
            - gnuplot
    - os: osx
      env: GNUPLOT=no
    - os: osx
      env: GNUPLOT=yes

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pip install 'travis-cargo<0.2' --user;
      export PATH=$HOME/.local/bin:$PATH;
      cargo install mdbook;
    fi

install:
  - sh ci/install.sh

script:
  - cargo build
  - cargo clippy
  - cargo test
  - cargo bench -- --test --nocapture
  - cargo doc --no-deps
  - cd macros && cargo build && cd ..

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$GNUPLOT" = "yes" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
      cd book;
      mdbook build;
      cd ..;
      cp -r book/book target/doc/book;
      travis-cargo doc-upload;
    fi

env:
  global:
    - secure: "f/HaMzQu7d6ochSjE5lUjJbXYWlhbzslyTuWq+Lub/r2TTL4hVlT9koC4RT7W73V3WDrwYIqEGmwvscVffnijZRebl/PV+6WlOlYJEdAgKxGROpFGDIJGRGAc/f3s6OcJ+Hr8rmRF70fYEl45hs6J53X8s+CVRuty+r/UdilRpM="

branches:
  only: master

notifications:
  email:
    on_success: never
