language: rust

env:
  global:
    - secure: C2Oij4OPM2pdkbpEV6bsCJ8PpqDk2NtjFhFiO+4ZlYrRCQnbv+TAOuWNj5aX1EOWPlMQdP/95VrEOizUcK1twsCuc6d8PnAoCu8WnLRsOSO8GftVynC+CEJSnaDpAVO3N23f5jrCsKQhZx9R/hADpY5ni2ik0rKNWGllaYzuUCc=

before_install:
  # This PPA has a newer version of gnuplot
  - sudo add-apt-repository ppa:gladky-anton/precise-backports -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gnuplot

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master

notifications:
  email:
    on_success: never
