before_install:
  - git clone --recursive https://github.com/rust-lang/cargo
  - yes | sudo add-apt-repository --yes ppa:hansjorg/rust
  - yes | sudo add-apt-repository ppa:gladky-anton/precise-backports
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq rust-nightly gnuplot
  - cd cargo && ./configure && make && sudo make install && cd .. && sudo rm -rf cargo

script:
  - make
  - make test

branches:
  only: master
