language: rust
sudo: false

env:
  global:
    - secure: LF3AmakbtH4MpNp2QOrc1DCHWsKCyLketO2QznHE2+eT+j4fHtrBKZMKXTFd5KiZ7rkuatIBHyutczNh4r8GGvhuHSogHAnzjD6I4201RkgoU1v8e36TTeMoZl2S9H04LOz4aNlT3nCBXecVG8jorVgIIvonJ60Vu2UDWWA5L/k=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
