language: rust

env:
  global:
    - secure: pQJkfFtkEXSTb/rx0rRbP9zuAbCI2NzEFNylWJlhGR3TN/bKo/RwDdl1Lc0L4JYFOxdk8hjNLSWJKA148+y4hU4rrkPX9NyfnUdbLz5vm6900PkT/aG8dceVWudkueC9fT0n4S67256DjkkTzhTwsdp8CBbrzgj/W7SAO8jZwv4=
  matrix:
    - WITH_GNUPLOT=true
    - WITH_GNUPLOT=false

before_install:
  # This PPA has a newer version of gnuplot
  - if [[ $WITH_GNUPLOT == 'true' ]]; then
      sudo add-apt-repository ppa:gladky-anton/precise-backports -y;
      sudo apt-get update -qq;
    fi

install:
  - if [[ $WITH_GNUPLOT == 'true' ]]; then
      sudo apt-get install -qq gnuplot;
    fi

script:
  - cargo build --verbose
  - cargo bench --verbose -- --test --nocapture
  - cargo doc --verbose && mv target/doc doc
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh'

branches:
  only: master
