sudo: false

language: rust

rust: nightly

os:
  - linux
  - osx

matrix:
  exclude:
    - os: linux
    - os: osx
  include:
    - os: linux
      env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            # Cross compiler and cross compiled C libraries
            - gcc-multilib
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      env: TARGET=i686-apple-darwin
    - os: osx
      env: TARGET=x86_64-apple-darwin

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

install:
  - sh ci/install.sh

script:
  - cargo build --target $TARGET
  - cargo test --target $TARGET
  - cargo doc --target $TARGET

after_success:
  - if [ "$TARGET" = "x86_64-unknown-linux-gnu" ]; then
      travis-cargo doc-upload;
    fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: D08wHRxR0AT2yx0yXOLWKhlAxDeV7XXRCMs7yrULom3iS0BKM2qviohpYNx0Jx5NyOC97ksAz6FZ3oSSURMjW/19L9bUjZimHOIVeKFDNBn4OmUASv2LywNgFfh56z8w3znuI0bs9JOGGcH3HozW/vTENDJs3SjB7lrzszrs45g=

branches:
  only: master

notifications:
  email:
    on_success: never
