[package]

authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "simplot"
version = "0.0.0"

[dependencies]
byteorder = "*"

[dependencies.cast]
git = "https://github.com/japaric/cast.rs"

[dependencies.zip]
git = "https://github.com/japaric/zip.rs"

[dev-dependencies]
rand = "*"

[dev-dependencies.complex]
git = "https://github.com/japaric/complex.rs"

[dev-dependencies.space]
git = "https://github.com/japaric/space.rs"
