[package]
name = "criterion"
version = "0.0.0"
authors = ["Jorge Aparicio <japaric@linux.com>"]

[dependencies]
log = "*"
time = "*"

[dependencies.criterion_macros]
path = "macros"

[dependencies.simplot]
git = "https://github.com/japaric/simplot.rs"

[dependencies.stats]
git = "https://github.com/japaric/stats.rs"
