[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "simplot"
version = "0.0.0"

[dependencies]
byteorder = "0.4.2"
cast = "0.1.0"
itertools = "0.4.7"

[dev-dependencies]
num = "0.1.30"
rand = "0.3.13"
