[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "stats"
version = "0.0.0"

[dependencies]
cast = "0.1.0"
floaty = "0.1.0"
num_cpus = "0.2.10"
rand = "0.3.13"
thread-scoped = "1.0.1"

[dev-dependencies]
itertools = "0.4.7"
quickcheck = "0.2.25"
quickcheck_macros = "0.2.25"

[dev-dependencies.approx]
git = "https://github.com/japaric/approx.rs"
