[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "criterion"
version = "0.0.0"

[dependencies]
log = "0.3.5"
rustc-serialize = "0.3.16"
time = "0.1.34"
walkdir = "0.1.5"

[dependencies.criterion_macros]
path = "macros"

[dependencies.simplot]
git = "https://github.com/japaric/simplot.rs"

[dependencies.space]
git = "https://github.com/japaric/space.rs"

[dependencies.stats]
branch = "no-simd"
git = "https://github.com/japaric/stats.rs"
