[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "criterion"
version = "0.0.0"

[dependencies]
criterion-stats = "0.1.0"
itertools = "0.4.7"
log = "0.3.5"
rustc-serialize = "0.3.16"

[dependencies.criterion-plot]
git = "https://github.com/japaric/simplot.rs"

[dev-dependencies]
criterion-macros = { path = "macros" }
walkdir = "0.1.5"
