[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>", "Brook Heisler"]
name = "criterion"
version = "0.1.0"

description = "Statistics-driven micro-benchmarking library"
homepage = "https://japaric.github.io/criterion.rs/book/index.html"
repository = "https://github.com/japaric/criterion.rs"
readme = "README.md"
keywords = ["criterion", "benchmark"]
categories = ["development-tools::profiling"]
license = "Apache-2.0/MIT"

[dependencies]
criterion-plot = { path="plot" }
criterion-stats = { path="stats" }
itertools = "0.4.7"
log = "0.3.5"
rustc-serialize = "0.3.16"

[dev-dependencies]
walkdir = "0.1.5"

[badges]
travis-ci = { repository = "japaric/criterion.rs" }
appveyor = { repository = "japaric/criterion.rs", id = "4255ads9ctpupcl2" }
maintenance = { status = "actively-maintained" }

[workspace]
