[package]
name = "criterion"
version = "0.0.0"
authors = ["Jorge Aparicio <japaric@linux.com>"]

[dependencies.criterion_macros]
path = "macros"

[dependencies.log]
git = "https://github.com/rust-lang/log"

[dependencies.rustc-serialize]
git = "https://github.com/rust-lang/rustc-serialize"

[dependencies.simplot]
git = "https://github.com/japaric/simplot.rs"

[dependencies.stats]
git = "https://github.com/japaric/stats.rs"

[dependencies.time]
git = "https://github.com/rust-lang/time"
