[package]

authors = ["Jorge Aparicio <japaricious@gmail.com>"]
name = "stats"
version = "0.0.0"

[dependencies]
num_cpus = "0.2.10"
rand = "0.3.13"
thread-scoped = "1.0.1"

[dependencies.cast]
git = "https://github.com/japaric/cast.rs"

[dependencies.float]
git = "https://github.com/japaric/float.rs"

[dev-dependencies.approx]
git = "https://github.com/japaric/approx.rs"

[dev-dependencies.quickcheck]
git = "https://github.com/burntsushi/quickcheck"

[dev-dependencies.quickcheck_macros]
git = "https://github.com/burntsushi/quickcheck"

[dev-dependencies.space]
git = "https://github.com/japaric/space.rs"
