[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>", "Brook Heisler <brookheisler@gmail.com>"]
name = "criterion"
version = "0.2.7"
edition = "2015"

description = "Statistics-driven micro-benchmarking library"
homepage = "https://bheisler.github.io/criterion.rs/book/index.html"
repository = "https://github.com/bheisler/criterion.rs"
readme = "README.md"
keywords = ["criterion", "benchmark"]
categories = ["development-tools::profiling"]
license = "Apache-2.0/MIT"

[dependencies]
lazy_static = "~1.1" # 1.1 is Required to ensure compatibility with rustc 1.20
criterion-plot = { path="plot", version="0.2.7", optional = true }
criterion-stats = { path="stats", version="0.3.0" }
failure = "0.1.3"
failure_derive = "0.1.3"
itertools = "0.7"
itertools-num = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0.82"
atty = "0.2.11"
clap = "2.32"
csv = "1.0"
walkdir = "2.2.7"
tinytemplate = { version = "1.0", path = "../tiny_template", optional = true }

[dev-dependencies]
tempdir = "0.3.7"

[badges]
travis-ci = { repository = "bheisler/criterion.rs" }
appveyor = { repository = "bheisler/criterion.rs", id = "4255ads9ctpupcl2" }
maintenance = { status = "passively-maintained" }

[features]
real_blackbox = []
html_reports = ["criterion-plot", "tinytemplate"]
default = ["html_reports"]

[workspace]

[[bench]]
name = "bench_main"
harness = false

[lib]
bench = false
