[package]

name = "simplot"
version = "0.0.0"
authors = ["Jorge Aparicio <japaric@linux.com>"]

[dev-dependencies.complex]
git = "https://github.com/japaric/complex.rs"

[dev-dependencies.space]
git = "https://github.com/japaric/space.rs"
