[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
description = "Criterion's plotting library"
documentation = "http://japaric.github.io/simplot.rs/criterion-plot"
keywords = ["plotting", "gnuplot", "criterion"]
license = "MIT OR Apache-2.0"
name = "criterion-plot"
repository = "https://github.com/japaric/simplot.rs"
version = "0.1.0"

[dependencies]
byteorder = "0.4.2"
cast = "0.1.0"
itertools = "0.4.7"

[dev-dependencies]
num = "0.1.30"
rand = "0.3.13"
