[package]
name = "criterion_bencher_compat"
version = "0.2.5"
authors = ["Brook Heisler <redattack34@gmail.com>"]

[dependencies]
criterion = { version = "0.2.5", path = ".." }

[[bench]]
name = "bencher_example"
harness = false

[workspace]